### ISSUE TITLE
1.12 suport

### ISSUE THREAD

**Issue by alvaro-octal** [YoFuzzy3/BungeePortals#29]
Got the following error on spigot 1.12 today's release 

```
[21:54:03] [Server thread/INFO]: [BungeePortals] Enabling BungeePortals v1.2
[21:54:03] [Server thread/INFO]: [BungeePortals] Disabling BungeePortals v1.2
[21:54:03] [Server thread/ERROR]: Error occurred while disabling BungeePortals v1.2 (Is it up to date?)
java.lang.NullPointerException: null
	at net.yofuzzy3.BungeePortals.BungeePortals.savePortalsData(BungeePortals.java:123) ~[?:?]
	at net.yofuzzy3.BungeePortals.BungeePortals.onDisable(BungeePortals.java:56) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.yofuzzy3.BungeePortals.BungeePortals.onEnable(BungeePortals.java:35) [BungeePortals.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
[21:54:03] [Server thread/ERROR]: Error occurred while enabling BungeePortals v1.2 (Is it up to date?)
java.lang.NullPointerException: [BungeePortals] WorldEdit not found, disabling...
	at net.yofuzzy3.BungeePortals.BungeePortals.onEnable(BungeePortals.java:36) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-ede465d-bb4ae3b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

**Comment by TheMolkaPL** [comment]
You need to install [WorldEdit](https://dev.bukkit.org/projects/worldedit) first.
