### ISSUE TITLE
Update for newer BungeeCord version?

### ISSUE THREAD

**Issue by xorinzor** [YoFuzzy3/BungeePortals#4]
When I start the BungeeCord server it throws these errors at me

    Could not load plugin from file plugins/BungeePortals.jar
    Cannot create property=description for JavaBean=PluginDescription(name=BungeePortals, main=null, version=1.1, author=null, depends=[], file=null)
     in 'reader', line 1, column 1:
        name: BungeePortals
        ^
    Unable to find property 'description' on class: net.md_5.bungee.api.plugin.PluginDescription
     in 'reader', line 3, column 14:
        description: Create portals of any shape or s ...
                     ^
    
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:299)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:189)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:332)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:182)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:141)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:127)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:481)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:475)
        at net.md_5.bungee.api.plugin.PluginManager.detectPlugins(PluginManager.java:307)
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:168)
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:68)
    Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'description' on class: net.md_5.bungee.api.plugin.PluginDescription
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:132)
        at org.yaml.snakeyaml.introspector.PropertyUtils.getProperty(PropertyUtils.java:121)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.getProperty(Constructor.java:309)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:240)
        ... 10 more

**Comment by TheMolkaPL** [comment]
BungeePortals is not a BungeeCord plugin.
